package com.example.ui.components

import androidx.annotation.DrawableRes
import com.example.R

/**
 * The bundled artwork for a country's flag (res/drawable-nodpi/flag_xx.webp), or null when a country has
 * none. Spelled out instead of looked up by name so a missing file is a compile error and the resource
 * shrinker keeps exactly these files. Generated by tools/gen-flag-art.py from the files present.
 */
@DrawableRes
fun flagArtFor(code: String): Int? = when (code) {
    "AQ" -> R.drawable.flag_aq
    "AR" -> R.drawable.flag_ar
    "AU" -> R.drawable.flag_au
    "BR" -> R.drawable.flag_br
    "CA" -> R.drawable.flag_ca
    "CL" -> R.drawable.flag_cl
    "CN" -> R.drawable.flag_cn
    "CO" -> R.drawable.flag_co
    "DE" -> R.drawable.flag_de
    "EG" -> R.drawable.flag_eg
    "ES" -> R.drawable.flag_es
    "FJ" -> R.drawable.flag_fj
    "FR" -> R.drawable.flag_fr
    "GB" -> R.drawable.flag_gb
    "GR" -> R.drawable.flag_gr
    "IN" -> R.drawable.flag_in
    "IT" -> R.drawable.flag_it
    "JP" -> R.drawable.flag_jp
    "KE" -> R.drawable.flag_ke
    "KR" -> R.drawable.flag_kr
    "MA" -> R.drawable.flag_ma
    "MX" -> R.drawable.flag_mx
    "NG" -> R.drawable.flag_ng
    "NO" -> R.drawable.flag_no
    "NZ" -> R.drawable.flag_nz
    "SA" -> R.drawable.flag_sa
    "SE" -> R.drawable.flag_se
    "TH" -> R.drawable.flag_th
    "TZ" -> R.drawable.flag_tz
    "UA" -> R.drawable.flag_ua
    "US" -> R.drawable.flag_us
    "VN" -> R.drawable.flag_vn
    "ZA" -> R.drawable.flag_za
    else -> null
}
