"""Regenerates FlagArt.kt from the flag files in res/drawable-nodpi, one `when` branch per flag_xx.webp."""
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FLAGS = REPO / 'app/src/main/res/drawable-nodpi'
OUT = REPO / 'app/src/main/java/com/example/ui/components/FlagArt.kt'

codes = sorted(p.stem[len('flag_'):].upper() for p in FLAGS.glob('flag_*.webp'))
branches = '\n'.join(f'    "{c}" -> R.drawable.flag_{c.lower()}' for c in codes)
OUT.write_text(f'''package com.example.ui.components

import androidx.annotation.DrawableRes
import com.example.R

/**
 * The bundled artwork for a country's flag (res/drawable-nodpi/flag_xx.webp), or null when a country has
 * none. Spelled out instead of looked up by name so a missing file is a compile error and the resource
 * shrinker keeps exactly these files. Generated by tools/gen-flag-art.py from the files present.
 */
@DrawableRes
fun flagArtFor(code: String): Int? = when (code) {{
{branches}
    else -> null
}}
''')
print(len(codes), 'branches written')
